- name: configuring the repo
  ansible.builtin.shell: curl -o /etc/yum.repos.d/redis.repo http://raw.githubusercontent.com/stans-robot-project/redis/main/redis.repo

- name: installing the redis  
  ansible.builtin.package:
    name: redis
    state: present

- name: enabling the permissions 
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: enabling the service
  systemd:
    name: redis
    state: restarted
    enabled: yes




