- name: configuring the repo
  ansible.builtin.copy:
    src: mongod.conf
    dest: /etc/yum.repos.d/mongodb.repo

- name: installing the mongod
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: enabling the service
  ansible.builtin.service:
    name: mongod
    state: restarted
    enabled: yes
    
- name: configuring the name
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}



  