- name: demo on root user
  hosts: all
  become: yes
  tasks: 
  - name: demo1
    ansible.builtin.shell: id
    register: OUT
  - name: printig tje variable
    ansible.builtin.debug:
      msg: "{{OUT}}"