- name: Demo on vars usage
  hosts: all
  vars:                                   # Global Variables : All the tasks of this play can access this variable
    URL: play.google.com
  vars_prompt:
    - name: URNAME
      prompt: Enter your name
      private: false
  tasks:
    - name: Printing the variable
      ansible.builtin.debug:
        msg: Value of the URL is {{URL}}

