#Installing Ngnix
- name: Installing Ngnix
  ansible.builtin.package:
    name: nginx
    state: present

## used to download and unzip the files, it unzips the file in /tmp folder (file name is frontend-main )
- name: Unarchive the files
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/frontend/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: deleting the existing files 
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: copying the files 
  ansible.builtin.copy:
    src: /tmp/frontend-main/static
    dest: /usr/share/nginx/html
    remote_src: yes

- name: copying the files 
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: restarting the servivce
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes
    daemon-reload: yes


