- name: Configuring the {{COMPONENT}} repo
  ansible.builtin.copy:
    src: "{{COMPONENT}}.repo"
    dest: /etc/yum.repos.d/{{COMPONENT}}.repo

- name: Installing {{COMPONENT}}
  ansible.builtin.package:
      name:
        - mysql-community-server
        - MySQL-python
        - python3-PyMySQL
      state: present

- name: Installing the {{COMPONENT}}
  ansible.builtin.package:
    name: mysql-community-server
    state: present

- name: Starting {{COMPONENT}}
  systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes