- name: configuring nodejs
  ansible.builtin.inclue:
   name: common 
   tasks_from: nodejs

- name: Add the user {{APPUSER}} with a specific uid and a primary group of 'admin'
  ansible.builtin.user:
    name: "{{APPUSER}}"

- name: downloading and extracting the {{COMPONENT}} 
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Cleaning the {{COMPONENT}}
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}
    state: absent
  ignore_errors: true

- name: copying {{COMPONENT}} user components
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main
    dest: /home/{{APPUSER}}/{{COMPONENT}}
    owner: "{{APPUSER}}"
    group: "{{APPUSER}}"
    remote_src: yes

- name: Generating Artifacts with npm install
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}/


- name: configuring the name
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}