- name: configuring nodejs
  ansible.builtin.shell: curl --silent --locaation https://rpm.nodesource.com/setup_16.x | sudo bash -

- name: installing the nodejs
  ansible.builtin.package:
    name: nodejs
    state: present

- name: Add the user {{APPUSER}} with a specific uid and a primary group of 'admin'
  ansible.builtin.user:
    name: "{{APPUSER}}"

- name: downloading and extracting the {{COMPONENT}} 
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Cleaning the {{COMPONENT}}
  ansible.builtin.file:
    path: /home/{{APPUSER}}/{{COMPONENT}}
    state: absent
  ignore_errors: true

- name: copying {{COMPONENT}} user components
  ansible.builtin.copy:
    path: /tmp/{{COMPONENT}}-main
    dest: /home/{{APPUSER}}/{{COMPONENT}}
    owner: "{{APPUSER}}"
    group: "{{APPUSER}}"
    remote_src: yes

- name: Installing npm 
  community.genral.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}



- name: configuring the name
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}