- name: configuring nodejs
  ansible.builtin.inclue:
   name: common 
   tasks_from: nodejs

- name: creating user
  ansible.builtin.inclue:
   name: common 
   tasks_from: create_user.yml

- name: downloading
  ansible.builtin.inclue:
   name: common 
   tasks_from: download.yml

- name: Generating Artifacts with npm install
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}/


- name: configuring the name
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}