- name: configuring the repo
  ansible.builtin.copy:
    src: mongod.conf
    dest: /etc/yum.repos.d/mongodb.repo

- name: installing the mongod
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: enabling the service
  systemd:
    name: mongod
    state: restarted
    enabled: yes
- name: enabling the permissions 
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.0'
    replace: '0.0.0.0'

- name: downloading and extracting the {{COMPONENT}} schema 
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/mongodb/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: Run a js file containing MongoDB commands with pseudo-idempotency
  community.mongodb.mongodb_shell:
    file: /etc/mongodb-main/{{item}}
    idempotent: yes
  loop:
    - catalogue.js
    - users.js

- name: configuring the name
  ansible.builtin.shell: set-hostname {{COMPONENT}}-{{ENV}}