- name: Creating App User
  ansible.builtin.include_role:
    name: common
    tasks_from: create_user

- name: Download and extracting {{COMPONENT}}
  ansible.builtin.include_role:
    name: common
    tasks_from: download_and_extract

- name: Generating Artifacts with npm install
  community.general.npm:
    path: /home/{{APPUSER}}/{{COMPONENT}}/

- name: Configuring {{COMPONENT}} Service
  ansible.builtin.include_role:
    name: common
    tasks_from: config_svc

- name: Configuring Name
  ansible.builtin.include_role:
    name: common
    tasks_from: set_name
